---
images_to_build:
  - name: ubuntu-ssh
    tag: latest
    path: "build_ubuntu"

  - name: almalinux-ssh
    tag: latest
    path: "build_almalinux"

pubkey_path: "{{ lookup('env','HOME') + '/.ssh/id_ed25519.pub' }}"
container_engine: "auto"
registry_host: "localhost"
registry_port: 5000

